title: Zhanibek's blog
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog: random thoughts and ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "isentropic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: isentropic
# breadcrumbs: true
# Build settings
show_excerpts: true
theme: minima
header_pages:
  - about.md
